"""Create a new Frappe document with permission-aware writes.

Sibling of ``update_doc``. The agent uses this when the user asks for a
new record ("create a customer Acme", "add a task for tomorrow").

Safety bounds (same shape as update_doc, adapted for create):

- Calling user must have ``create`` permission on the target DocType
  (``frappe.has_permission(doctype, ptype="create")``). Record-level
  perms don't apply yet - no record exists.
- System fields are refused: ``owner``, ``creation``, ``modified``,
  ``modified_by``, ``doctype``, ``docstatus``, ``idx``, ``parent``,
  ``parentfield``, ``parenttype``. ``name`` is **allowed** so DocTypes
  with autoname=prompt / field-derived autoname work - Frappe's autoname
  machinery decides whether to honour it.
- Empty ``values`` dict is refused - agents shouldn't create blank rows.
- The DocType's validate() and on_insert() hooks fire via ``doc.insert()``,
  so required fields, link integrity, and business rules apply.
"""

import frappe

from jarvis.exceptions import InvalidArgumentError, PermissionDeniedError

# `name` is intentionally NOT in this list: DocTypes that use autoname=prompt
# (or autoname=field:<x>) need it set in `values`. Frappe's autoname handling
# decides whether to use or ignore the supplied name.
PROTECTED_FIELDS = frozenset({
    "owner",
    "creation",
    "modified",
    "modified_by",
    "doctype",
    "docstatus",
    "idx",
    "parent",
    "parentfield",
    "parenttype",
})


def _validate_create_args(doctype: str, values: dict) -> None:
    """Shared guards for create-shaped payloads (create_doc + preview_doc):
    non-empty args, no protected fields, create permission."""
    if not doctype:
        raise InvalidArgumentError("doctype is required")
    if not isinstance(values, dict) or not values:
        raise InvalidArgumentError("values must be a non-empty dict")

    protected = sorted(set(values.keys()) & PROTECTED_FIELDS)
    if protected:
        raise InvalidArgumentError(
            f"refusing to write protected field(s): {', '.join(protected)}"
        )

    if not frappe.has_permission(doctype, ptype="create"):
        raise PermissionDeniedError(
            f"no create permission on {doctype}"
        )


def create_doc(doctype: str, values: dict) -> dict:
    """Insert a new document with ``values`` and return it.

    Returns the inserted document as a dict (matching ``get_doc``'s shape),
    including the autogenerated ``name``. Raises:
      - InvalidArgumentError on empty args, empty values, attempts to
        write protected fields
      - PermissionDeniedError when the calling user lacks create on the DocType
      - frappe.ValidationError when the DocType's own validate() rejects
        (missing required fields, link integrity, etc.)
    """
    _validate_create_args(doctype, values)

    doc = frappe.new_doc(doctype)
    for field, value in values.items():
        doc.set(field, value)
    _set_title_from_title_field(doc)
    doc.insert()  # runs DocType validate() + on_insert hooks; sets autoname
    return doc.as_dict()


def _set_title_from_title_field(doc) -> None:
    """Materialize an empty ``title`` from the doctype's ``title_field``.

    Desk forms historically filled ``title`` via a templated default (e.g.
    ``{supplier_name}`` on invoices); newer schemas dropped the template and
    point ``title_field`` at the source field instead, leaving the stored
    ``title`` column blank on API-created records - visibly inconsistent
    next to older data and any print/report that reads ``title``. Filling
    it with the ``title_field`` value just persists what Frappe would
    display anyway; explicit caller values always win."""
    try:
        meta = doc.meta
        tf = meta.get("title_field")
        if (
            tf
            and tf != "title"
            and meta.has_field("title")
            and not doc.get("title")
            and doc.get(tf)
        ):
            doc.set("title", doc.get(tf))
    except Exception:
        pass  # cosmetic best-effort; never block the insert
